// Generated by CoffeeScript 1.5.0
(function() {

  window.TY = {};

  TY.lookForNewMessage = function() {
    var areNews, howMany;
    console.log("tweet yeller checking...");
    areNews = $('.new-tweets-bar:visible');
    if (areNews.length < 1) {
      return "see ya next loop";
    }
    howMany = $('.new-tweets-bar:visible').data('itemCount');
    areNews.click();
    return this.collectNewTweets(howMany);
  };

  TY.collectNewTweets = function(lastN) {
    var collected, lastTweets;
    lastTweets = $(".stream.home-stream .stream-items li.stream-item:lt(" + lastN + ")");
    collected = [];
    lastTweets.each(function(i, el) {
      var jel, msgObj, textEl;
      msgObj = {};
      jel = $(el);
      msgObj.author = jel.find('.stream-item-header .fullname').text();
      textEl = jel.find('.tweet-text').clone();
      textEl.find('a').each(function(i, a) {
        var ja;
        ja = $(a);
        if (ja.is(".twitter-timeline-link")) {
          return ja.text("link to " + ja.find(".js-display-url").text().replace(/\..*/g, ""));
        }
      });
      msgObj.text = textEl.text().replace(/\#/g, 'hashtag ').replace(/\@/g, 'at ');
      return collected.push(msgObj);
    });
    return this.transmit(collected);
  };

  TY.transmit = function(tweetList) {
    console.log(tweetList);
    return chrome.runtime.sendMessage({
      readThose: tweetList
    }, function(response) {
      return console.log(response.msg);
    });
  };

  setInterval(TY.lookForNewMessage.bind(TY), 1000);

  setTimeout(function() {
    return TY.collectNewTweets(3);
  }, 3000);

}).call(this);
