// Generated by CoffeeScript 1.5.0
(function() {

  $(function(e) {
    var isMute;
    $('#mute-ckb').click(function() {
      var isChecked;
      isChecked = $(this).is(':checked');
      if (isChecked) {
        localStorage.setItem('mute', 'yes');
      } else {
        localStorage.setItem('mute', 'no');
      }
      return chrome.tabs.reload();
    });
    isMute = localStorage.getItem('mute') === 'yes' ? true : false;
    return $('#mute-ckb').prop('checked', isMute);
  });

}).call(this);
