// Generated by CoffeeScript 1.5.0
(function() {

  chrome.runtime.onMessage.addListener(function(req, sender, res) {
    var msg, say, _i, _len, _ref;
    say = function(author, msg) {
      chrome.tts.speak("" + author + " said", {
        'enqueue': true
      });
      return chrome.tts.speak(msg, {
        'enqueue': true
      });
    };
    console.log(req);
    say("You got " + req.readThose.length + " new tweets,", " ");
    _ref = req.readThose;
    for (_i = 0, _len = _ref.length; _i < _len; _i++) {
      msg = _ref[_i];
      say(msg.author, msg.text);
    }
    return res({
      msg: "reading or whatever"
    });
  });

}).call(this);
