// Generated by CoffeeScript 1.5.0
(function() {

  chrome.runtime.onMessage.addListener(function(req, sender, res) {
    var i, msg, say, _i, _len, _ref;
    say = function(author, msg) {
      chrome.tts.speak("" + author + " said", {
        'enqueue': true
      });
      return chrome.tts.speak(msg, {
        'enqueue': true
      });
    };
    console.log(req);
    chrome.tts.speak("You got " + req.readThose.length + " new tweets,");
    _ref = req.readThose;
    for (i = _i = 0, _len = _ref.length; _i < _len; i = ++_i) {
      msg = _ref[i];
      say(msg.author, msg.text);
      if (i !== req.readThose.length - 1) {
        chrome.tts.speak('next,', {
          'enqueue': true
        });
      }
    }
    return res({
      msg: "reading or whatever"
    });
  });

}).call(this);
